server:
  port: 8080

spring:
  config:
    import: "configserver:"
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: booking-service
          uri: lb://BOOKING-SERVICE
          predicates:
            - Path=/api/bookings/**
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**
        - id: charging-service
          uri: lb://CHARGING-SERVICE
          predicates:
            - Path=/api/charging/**
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/payments/**
        - id: statistics-service
          uri: lb://STATISTICS-SERVICE
          predicates:
            - Path=/api/statistics/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ 